/*
 Copyright 2016 Google Inc. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Names of the two caches used in this version of the service worker.
// Change to v2, etc. when you update any of the local resources, which will
// in turn trigger the install event again.
const PRECACHE = 'precache-v1';
const RUNTIME = 'runtime';

// A list of local resources we always want to be cached.
const PRECACHE_URLS = [
  './',
  'index.html',
  'style.css',
  'script.js',
  'data.js',
  'game.js',
  'lib/jquery.min.js',
  '3party/font-awesome/css/fontawesome.css',
  '3party/font-awesome/css/solid.css',
  '3party/font-awesome/webfonts/fa-solid-900.woff2',
  '3party/font-awesome/webfonts/fa-solid-900.ttf',
  'play',
  'play/',
  'play/?g=world',
  'play/?g=africa',
  'play/?g=americas',
  'play/?g=asia',
  'play/?g=europe',
  'play/?g=oceania',
  'play/?g=eu',
  'play/?g=us',
  'play/?g=de',
  'play/?g=es',
  'play/index.html',
  'play/style.css',
  'play/script.js',
  'view',
  'view/',
  'view/?g=world',
  'view/?g=africa',
  'view/?g=americas',
  'view/?g=asia',
  'view/?g=europe',
  'view/?g=oceania',
  'view/?g=eu',
  'view/?g=us',
  'view/?g=de',
  'view/?g=es',
  'view/index.html',
  'view/style.css',
  'view/script.js',
  'img/flag/ab.svg',
  'img/flag/ae.svg',
  'img/flag/af.svg',
  'img/flag/ag.svg',
  'img/flag/al.svg',
  'img/flag/am.svg',
  'img/flag/ao.svg',
  'img/flag/ar.svg',
  'img/flag/as.svg',
  'img/flag/at.svg',
  'img/flag/au.svg',
  'img/flag/aw.svg',
  'img/flag/az.svg',
  'img/flag/ba.svg',
  'img/flag/bb.svg',
  'img/flag/bd.svg',
  'img/flag/be.svg',
  'img/flag/bf.svg',
  'img/flag/bg.svg',
  'img/flag/bh.svg',
  'img/flag/bi.svg',
  'img/flag/bj.svg',
  'img/flag/bm.svg',
  'img/flag/bn.svg',
  'img/flag/bo.svg',
  'img/flag/br.svg',
  'img/flag/bs.svg',
  'img/flag/bt.svg',
  'img/flag/bw.svg',
  'img/flag/by.svg',
  'img/flag/bz.svg',
  'img/flag/ca.svg',
  'img/flag/cd.svg',
  'img/flag/cf.svg',
  'img/flag/cg.svg',
  'img/flag/ch.svg',
  'img/flag/ci.svg',
  'img/flag/ck.svg',
  'img/flag/cl.svg',
  'img/flag/cm.svg',
  'img/flag/cn.svg',
  'img/flag/co.svg',
  'img/flag/cr.svg',
  'img/flag/cu.svg',
  'img/flag/cv.svg',
  'img/flag/cy.svg',
  'img/flag/cz.svg',
  'img/flag/de.svg',
  'img/flag/de-bb.svg',
  'img/flag/de-be.svg',
  'img/flag/de-bw.svg',
  'img/flag/de-by.svg',
  'img/flag/de-hb.svg',
  'img/flag/de-he.svg',
  'img/flag/de-hh.svg',
  'img/flag/de-mv.svg',
  'img/flag/de-ni.svg',
  'img/flag/de-nw.svg',
  'img/flag/de-rp.svg',
  'img/flag/de-sh.svg',
  'img/flag/de-sl.svg',
  'img/flag/de-sn.svg',
  'img/flag/de-st.svg',
  'img/flag/de-th.svg',
  'img/flag/dj.svg',
  'img/flag/dk.svg',
  'img/flag/dm.svg',
  'img/flag/do.svg',
  'img/flag/dz.svg',
  'img/flag/ec.svg',
  'img/flag/ee.svg',
  'img/flag/eg.svg',
  'img/flag/er.svg',
  'img/flag/es.svg',
  'img/flag/es-an.svg',
  'img/flag/es-ar.svg',
  'img/flag/es-as.svg',
  'img/flag/es-cb.svg',
  'img/flag/es-ce.svg',
  'img/flag/es-cl.svg',
  'img/flag/es-cm.svg',
  'img/flag/es-cn.svg',
  'img/flag/es-ct.svg',
  'img/flag/es-ex.svg',
  'img/flag/es-ga.svg',
  'img/flag/es-ib.svg',
  'img/flag/es-mc.svg',
  'img/flag/es-md.svg',
  'img/flag/es-ml.svg',
  'img/flag/es-nc.svg',
  'img/flag/es-pv.svg',
  'img/flag/es-ri.svg',
  'img/flag/es-vc.svg',
  'img/flag/et.svg',
  'img/flag/fi.svg',
  'img/flag/fj.svg',
  'img/flag/fm.svg',
  'img/flag/fo.svg',
  'img/flag/fr.svg',
  'img/flag/ga.svg',
  'img/flag/gb.svg',
  'img/flag/gd.svg',
  'img/flag/ge.svg',
  'img/flag/gh.svg',
  'img/flag/gi.svg',
  'img/flag/gl.svg',
  'img/flag/gm.svg',
  'img/flag/gn.svg',
  'img/flag/gq.svg',
  'img/flag/gr.svg',
  'img/flag/gt.svg',
  'img/flag/gu.svg',
  'img/flag/gw.svg',
  'img/flag/gy.svg',
  'img/flag/hk.svg',
  'img/flag/hn.svg',
  'img/flag/hr.svg',
  'img/flag/ht.svg',
  'img/flag/hu.svg',
  'img/flag/id.svg',
  'img/flag/ie.svg',
  'img/flag/il.svg',
  'img/flag/im.svg',
  'img/flag/in.svg',
  'img/flag/iq.svg',
  'img/flag/ir.svg',
  'img/flag/is.svg',
  'img/flag/it.svg',
  'img/flag/jm.svg',
  'img/flag/jo.svg',
  'img/flag/jp.svg',
  'img/flag/ke.svg',
  'img/flag/kg.svg',
  'img/flag/kh.svg',
  'img/flag/ki.svg',
  'img/flag/km.svg',
  'img/flag/kn.svg',
  'img/flag/kp.svg',
  'img/flag/kr.svg',
  'img/flag/kw.svg',
  'img/flag/ky.svg',
  'img/flag/kz.svg',
  'img/flag/la.svg',
  'img/flag/lb.svg',
  'img/flag/lc.svg',
  'img/flag/li.svg',
  'img/flag/lk.svg',
  'img/flag/lr.svg',
  'img/flag/ls.svg',
  'img/flag/lt.svg',
  'img/flag/lu.svg',
  'img/flag/lv.svg',
  'img/flag/ly.svg',
  'img/flag/ma.svg',
  'img/flag/mc.svg',
  'img/flag/md.svg',
  'img/flag/me.svg',
  'img/flag/mg.svg',
  'img/flag/mh.svg',
  'img/flag/mk.svg',
  'img/flag/ml.svg',
  'img/flag/mm.svg',
  'img/flag/mn.svg',
  'img/flag/mo.svg',
  'img/flag/mr.svg',
  'img/flag/mt.svg',
  'img/flag/mu.svg',
  'img/flag/mv.svg',
  'img/flag/mw.svg',
  'img/flag/mx.svg',
  'img/flag/my.svg',
  'img/flag/mz.svg',
  'img/flag/na.svg',
  'img/flag/ne.svg',
  'img/flag/ng.svg',
  'img/flag/ni.svg',
  'img/flag/nl.svg',
  'img/flag/no.svg',
  'img/flag/np.svg',
  'img/flag/nr.svg',
  'img/flag/nz.svg',
  'img/flag/om.svg',
  'img/flag/pa.svg',
  'img/flag/pe.svg',
  'img/flag/pg.svg',
  'img/flag/ph.svg',
  'img/flag/pk.svg',
  'img/flag/pl.svg',
  'img/flag/pr.svg',
  'img/flag/pt.svg',
  'img/flag/pw.svg',
  'img/flag/py.svg',
  'img/flag/qa.svg',
  'img/flag/ro.svg',
  'img/flag/rs.svg',
  'img/flag/ru.svg',
  'img/flag/rw.svg',
  'img/flag/sa.svg',
  'img/flag/sb.svg',
  'img/flag/sc.svg',
  'img/flag/sd.svg',
  'img/flag/se.svg',
  'img/flag/sg.svg',
  'img/flag/si.svg',
  'img/flag/sk.svg',
  'img/flag/sl.svg',
  'img/flag/sm.svg',
  'img/flag/sn.svg',
  'img/flag/so.svg',
  'img/flag/sr.svg',
  'img/flag/ss.svg',
  'img/flag/st.svg',
  'img/flag/sv.svg',
  'img/flag/sy.svg',
  'img/flag/sz.svg',
  'img/flag/td.svg',
  'img/flag/tg.svg',
  'img/flag/th.svg',
  'img/flag/tj.svg',
  'img/flag/tl.svg',
  'img/flag/tm.svg',
  'img/flag/tn.svg',
  'img/flag/to.svg',
  'img/flag/tr.svg',
  'img/flag/tt.svg',
  'img/flag/tv.svg',
  'img/flag/tw.svg',
  'img/flag/tz.svg',
  'img/flag/ua.svg',
  'img/flag/ug.svg',
  'img/flag/us.svg',
  'img/flag/us-ak.svg',
  'img/flag/us-al.svg',
  'img/flag/us-ar.svg',
  'img/flag/us-az.svg',
  'img/flag/us-ca.svg',
  'img/flag/us-co.svg',
  'img/flag/us-ct.svg',
  'img/flag/us-de.svg',
  'img/flag/us-fl.svg',
  'img/flag/us-ga.svg',
  'img/flag/us-hi.svg',
  'img/flag/us-ia.svg',
  'img/flag/us-id.svg',
  'img/flag/us-il.svg',
  'img/flag/us-in.svg',
  'img/flag/us-ks.svg',
  'img/flag/us-ky.svg',
  'img/flag/us-la.svg',
  'img/flag/us-ma.svg',
  'img/flag/us-md.svg',
  'img/flag/us-me.svg',
  'img/flag/us-mi.svg',
  'img/flag/us-mn.svg',
  'img/flag/us-mo.svg',
  'img/flag/us-ms.svg',
  'img/flag/us-mt.svg',
  'img/flag/us-nc.svg',
  'img/flag/us-nd.svg',
  'img/flag/us-ne.svg',
  'img/flag/us-nh.svg',
  'img/flag/us-nj.svg',
  'img/flag/us-nm.svg',
  'img/flag/us-nv.svg',
  'img/flag/us-ny.svg',
  'img/flag/us-oh.svg',
  'img/flag/us-ok.svg',
  'img/flag/us-or.svg',
  'img/flag/us-pa.svg',
  'img/flag/us-ri.svg',
  'img/flag/us-sc.svg',
  'img/flag/us-sd.svg',
  'img/flag/us-tn.svg',
  'img/flag/us-tx.svg',
  'img/flag/us-ut.svg',
  'img/flag/us-va.svg',
  'img/flag/us-vt.svg',
  'img/flag/us-wa.svg',
  'img/flag/us-wi.svg',
  'img/flag/us-wv.svg',
  'img/flag/us-wy.svg',
  'img/flag/uy.svg',
  'img/flag/uz.svg',
  'img/flag/va.svg',
  'img/flag/vc.svg',
  'img/flag/ve.svg',
  'img/flag/vg.svg',
  'img/flag/vi.svg',
  'img/flag/vn.svg',
  'img/flag/vu.svg',
  'img/flag/ws.svg',
  'img/flag/xk.svg',
  'img/flag/ye.svg',
  'img/flag/za.svg',
  'img/flag/zm.svg',
  'img/flag/zw.svg'
];

// The install handler takes care of precaching the resources we always need.
self.addEventListener('install', event => {
  console.log('Service Worker installing.');
  
  event.waitUntil(
    caches.open(PRECACHE)
      .then(cache => cache.addAll(PRECACHE_URLS))
      .then(self.skipWaiting())
  );
});

// The activate handler takes care of cleaning up old caches.
self.addEventListener('activate', event => {
  console.log('Service Worker activating.');
  
  const currentCaches = [PRECACHE, RUNTIME];
  event.waitUntil(
    caches.keys().then(cacheNames => {
      return cacheNames.filter(cacheName => !currentCaches.includes(cacheName));
    }).then(cachesToDelete => {
      return Promise.all(cachesToDelete.map(cacheToDelete => {
        return caches.delete(cacheToDelete);
      }));
    }).then(() => self.clients.claim())
  );
});

// The fetch handler serves responses for same-origin resources from a cache.
// If no response is found, it populates the runtime cache with the response
// from the network before returning it to the page.
self.addEventListener('fetch', event => {
  // Skip cross-origin requests, like those for Google Analytics.
  if (event.request.url.startsWith(self.location.origin)) {
    event.respondWith(
      caches.match(event.request).then(cachedResponse => {
        if (cachedResponse) {
          return cachedResponse;
        }

        return caches.open(RUNTIME).then(cache => {
          return fetch(event.request).then(response => {
            // Put a copy of the response in the runtime cache.
            return cache.put(event.request, response.clone()).then(() => {
              return response;
            });
          });
        });
      })
    );
  }
});
